=== SCAI-Lab/ord_schemas/schema/omh/sleep-period-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "This schema represents one sleep event.",
    "references": [
        {
            "description": "The SNOMED code represents Sleep, function (observable entity)",
            "url": "http://purl.bioontology.org/ontology/SNOMEDCT/258158006"
        }
    ],

    "definitions": {
        "unit_value": {
            "$ref": "unit-value-1.x.json"
        },
        "duration_unit_value": {
            "$ref": "duration-unit-value-1.x.json"
        },
        "time_frame": {
            "$ref": "time-frame-1.x.json"
        },
        "date_time": {
            "$ref": "date-time-1.x.json"
        }
    },

    "properties": {
        "initial_sleep_onset_time": {
            "$ref": "#/definitions/date_time"
        },
        "final_awakening_time": {
            "$ref": "#/definitions/date_time"
        },
        "latency_to_sleep_onset": {
            "$ref": "#/definitions/duration_unit_value"
        },
        "latency_to_arising": {
            "$ref": "#/definitions/duration_unit_value"
        },
        "total_sleep_period_duration": {
            "description": "From initial_sleep_onset_time to final_awakening_time.",
            "$ref": "#/definitions/duration_unit_value"
        },
        "total_sleep_time": {
            "description": "The total amount of time spent asleep.",
            "$ref": "#/definitions/duration_unit_value"
        },
        "number_of_awakenings": {
            "type": "integer"
        },
        "is_main_sleep": {
            "type": "boolean"
        },
        "sleep_maintenance_efficiency_percentage": {
            "description": "The amount of time spent asleep as a percentage of the sleep period.",
            "allOf": [
                {
                    "$ref": "#/definitions/unit_value"
                },
                {
                    "properties": {
                        "unit": {
                            "enum": ["%"]
                        }
                    }
                }
            ]
        }
    },
    "required": [
        "initial_sleep_onset_time",
        "final_awakening_time"
    ]
}

=== SCAI-Lab/ord_schemas/test-data/omh/sleep-period/1.0/shouldPass/valid-sleep-period.json
{

    "initial_sleep_onset_time": "2016-02-05T21:35:00Z",
    "final_awakening_time": "2016-02-06T06:35:00Z",
    "latency_to_sleep_onset": {
        "value": 17.5,
        "unit": "min"
    },
    "latency_to_arising": {
        "value": 5.2,
        "unit": "min"
    },
    "total_sleep_period_duration": {
        "value": 9,
        "unit": "h"
    },
    "total_sleep_time": {
        "value": 8.5,
        "unit": "h"
    },
    "number_of_awakenings": 1,
    "is_main_sleep": true,
    "sleep_maintenance_efficiency_percentage": {
        "value": 94.4,
        "unit": "%"
    }

}
